### ISSUE TITLE
言語を指定した直後でないとスクリプトが動かない

### ISSUE THREAD

**Issue by key-moon** [null-null-programming/AtCoderColorNEWS#2]
ここの`/?lang=ja`が不要なはずです
https://github.com/null-null-programming/AtCoderColorNEWS/blob/6c527cf6d8a7d3b0b06b1d230816d5da52bdb8ab/AtCoderColorNEWS.js#L6

**Comment by null-null-programming** [comment]
ご指摘ありがとうございます。変更します。

**Comment by null-null-programming** [comment]
修正しました。
